pipeline:
  debug:
    image: debian:stable-slim
    commands:
      - echo $DRONE_COMMIT_REF
      - echo $DRONE_COMMIT_SHA
  build:
    image: debian:stable-slim
    commands:
      - echo hello bitbucket3
